import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:image_picker/image_picker.dart';
import '../../data/repositories/item_repository_providers.dart';
import '../../data/repositories/storage_repository.dart';
import '../../domain/entities/item.dart';
import '../../domain/entities/item_status.dart';
import '../../services/auth_providers.dart';
import '../../services/local_notification_service.dart';
import '../../utils/error_handler.dart';
import '../widgets/success_animation.dart';

class CreateItemScreen extends ConsumerStatefulWidget {
  final String? initialBorrowerName;
  
  const CreateItemScreen({
    super.key,
    this.initialBorrowerName,
  });

  @override
  ConsumerState<CreateItemScreen> createState() => _CreateItemScreenState();
}

class _CreateItemScreenState extends ConsumerState<CreateItemScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _borrowerNameController = TextEditingController();
  final _borrowerContactController = TextEditingController();
  
  DateTime _lentAt = DateTime.now();
  DateTime? _dueAt;
  DateTime? _reminderAt;
  String? _category;
  
  final List<File> _selectedImages = [];
  bool _isLoading = false;
  
  // Predefined categories
  static const List<String> _predefinedCategories = [
    'Books',
    'Tools',
    'Electronics',
    'Clothing',
    'Games',
    'Other',
  ];

  @override
  void initState() {
    super.initState();
    if (widget.initialBorrowerName != null) {
      _borrowerNameController.text = widget.initialBorrowerName!;
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    _borrowerNameController.dispose();
    _borrowerContactController.dispose();
    super.dispose();
  }

  Future<void> _pickImages() async {
    try {
      ImageSource? source;
      
      // On web (Edge), directly use gallery without showing dialog
      if (kIsWeb) {
        source = ImageSource.gallery;
      } else {
        // Show dialog to choose source on other platforms
        source = await showDialog<ImageSource>(
          context: context,
          builder: (context) => AlertDialog(
            title: const Text('Select Image Source'),
            content: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                ListTile(
                  leading: const Icon(Icons.camera_alt),
                  title: const Text('Camera'),
                  onTap: () => Navigator.pop(context, ImageSource.camera),
                ),
                ListTile(
                  leading: const Icon(Icons.photo_library),
                  title: const Text('Gallery'),
                  onTap: () => Navigator.pop(context, ImageSource.gallery),
                ),
              ],
            ),
          ),
        );
      }

      if (source == null) return;

      final ImagePicker picker = ImagePicker();
      final XFile? image = await picker.pickImage(
        source: source,
        imageQuality: 85, // Compress to 85% quality
        maxWidth: 1920, // Max width
      );

      if (image != null) {
        setState(() {
          _selectedImages.add(File(image.path));
        });
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(ErrorHandler.getUserFriendlyMessage(e)),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  Future<void> _handleSave() async {
    if (!_formKey.currentState!.validate()) {
      HapticFeedback.lightImpact();
      return;
    }

    HapticFeedback.mediumImpact();
    setState(() {
      _isLoading = true;
    });

    try {
      final authState = ref.read(authStateProvider);
      final user = authState.value;
      
      if (user == null) {
        throw Exception('User not authenticated');
      }

      final repository = ref.read(itemRepositoryProvider);
      final storageRepo = ref.read(storageRepositoryProvider);
      
      // Create item first (without photos)
      final item = Item(
        id: '', // Will be generated by database
        userId: user.id,
        title: _titleController.text.trim(),
        description: _descriptionController.text.trim().isEmpty 
            ? null 
            : _descriptionController.text.trim(),
        borrowerName: _borrowerNameController.text.trim(),
        borrowerContact: _borrowerContactController.text.trim().isEmpty 
            ? null 
            : _borrowerContactController.text.trim(),
        lentAt: _lentAt,
        dueAt: _dueAt,
        reminderAt: _reminderAt,
        status: ItemStatus.lent,
        returnedAt: null,
        photoUrls: null,
        category: _category,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      final createdItem = await repository.createItem(userId: user.id, item: item);

      // Upload photos if any
      if (_selectedImages.isNotEmpty) {
        final PhotoUploadResult uploadResult = await storageRepo.uploadPhotos(
          userId: user.id,
          itemId: createdItem.id,
          imageFiles: _selectedImages,
        );

        // Update item with successfully uploaded photo URLs
        if (uploadResult.successfulUrls.isNotEmpty) {
          await repository.updateItem(
            userId: user.id,
            itemId: createdItem.id,
            updates: {
              'photo_urls': uploadResult.successfulUrls,
            },
          );
        }

        // Show error messages if any uploads failed
        if (uploadResult.hasErrors && mounted) {
          final errorMessages = uploadResult.errors
              .map((e) => '${e.fileName}: ${e.error}')
              .join('\n');
          
          final message = uploadResult.isPartialSuccess
              ? 'Some photos failed to upload:\n$errorMessages'
              : 'All photos failed to upload:\n$errorMessages';
          
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(message),
              backgroundColor: Colors.orange,
              duration: const Duration(seconds: 5),
              action: SnackBarAction(
                label: 'Dismiss',
                textColor: Colors.white,
                onPressed: () {},
              ),
            ),
          );
        }
      }

      // Schedule notification if reminder is set
      if (_reminderAt != null) {
        final notificationService = LocalNotificationService();
        await notificationService.scheduleReminder(
          id: createdItem.id.hashCode,
          title: 'Item Reminder',
          body: 'Don\'t forget: ${createdItem.title}',
          scheduledDate: _reminderAt!,
          payload: createdItem.id,
        );
      }

      if (mounted) {
        HapticFeedback.mediumImpact();
        SuccessAnimation.show(
          context,
          'Item created successfully!',
          onComplete: () {
            Navigator.pop(context);
          },
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(ErrorHandler.getUserFriendlyMessage(e)),
            backgroundColor: Colors.red,
            action: ErrorHandler.isRecoverable(e)
                ? SnackBarAction(
                    label: 'Retry',
                    textColor: Colors.white,
                    onPressed: _handleSave,
                  )
                : null,
          ),
        );
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Add Item'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Form(
          key: _formKey,
          autovalidateMode: AutovalidateMode.onUserInteraction,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const SizedBox(height: 8),
              TextFormField(
                controller: _titleController,
                decoration: const InputDecoration(
                  labelText: 'Item Name *',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.inventory_2),
                ),
                autovalidateMode: AutovalidateMode.onUserInteraction,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter item name';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _descriptionController,
                decoration: const InputDecoration(
                  labelText: 'Description (optional)',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.description),
                ),
                maxLines: 3,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _borrowerNameController,
                decoration: const InputDecoration(
                  labelText: 'Borrower Name *',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.person),
                ),
                autovalidateMode: AutovalidateMode.onUserInteraction,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter borrower name';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _borrowerContactController,
                decoration: const InputDecoration(
                  labelText: 'Borrower Contact (optional)',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.phone),
                ),
                keyboardType: TextInputType.emailAddress,
              ),
              const SizedBox(height: 16),
              // Category selector
              _buildCategorySelector(context),
              const SizedBox(height: 20),
              _buildDatePickerTile(
                context,
                title: 'Date Lent',
                value: DateFormat('MMM d, y').format(_lentAt),
                icon: Icons.calendar_today,
                onTap: () async {
                  final date = await showDatePicker(
                    context: context,
                    initialDate: _lentAt,
                    firstDate: DateTime(2000),
                    lastDate: DateTime.now(),
                  );
                  if (date != null) {
                    setState(() {
                      _lentAt = date;
                    });
                  }
                },
              ),
              const SizedBox(height: 16),
              _buildDatePickerTile(
                context,
                title: 'Due Date (optional)',
                value: _dueAt != null 
                    ? DateFormat('MMM d, y').format(_dueAt!) 
                    : 'Not set',
                icon: Icons.event,
                hasClear: _dueAt != null,
                onClear: () {
                  setState(() {
                    _dueAt = null;
                  });
                },
                onTap: () async {
                  final date = await showDatePicker(
                    context: context,
                    initialDate: _dueAt ?? DateTime.now(),
                    firstDate: DateTime.now(),
                    lastDate: DateTime.now().add(const Duration(days: 365)),
                  );
                  if (date != null) {
                    setState(() {
                      _dueAt = date;
                    });
                  }
                },
              ),
              const SizedBox(height: 16),
              _buildDatePickerTile(
                context,
                title: 'Reminder (optional)',
                value: _reminderAt != null 
                    ? DateFormat('MMM d, y h:mm a').format(_reminderAt!) 
                    : 'Not set',
                icon: Icons.notifications,
                hasClear: _reminderAt != null,
                onClear: () {
                  setState(() {
                    _reminderAt = null;
                  });
                },
                onTap: () async {
                  final date = await showDatePicker(
                    context: context,
                    initialDate: _reminderAt ?? DateTime.now(),
                    firstDate: DateTime.now(),
                    lastDate: DateTime.now().add(const Duration(days: 365)),
                  );
                  
                  if (date == null || !mounted) return;
                  
                  final navigatorContext = context;
                  final time = await showTimePicker(
                    context: navigatorContext,
                    initialTime: TimeOfDay.fromDateTime(_reminderAt ?? DateTime.now()),
                  );
                  
                  if (time == null || !mounted) return;
                  
                  final reminderAt = DateTime(
                    date.year,
                    date.month,
                    date.day,
                    time.hour,
                    time.minute,
                  );
                  
                  // Validate that reminder is in the future
                  if (reminderAt.isBefore(DateTime.now())) {
                    if (!mounted) return;
                    ScaffoldMessenger.of(navigatorContext).showSnackBar(
                      const SnackBar(
                        content: Text('Reminder date must be in the future'),
                        backgroundColor: Colors.red,
                      ),
                    );
                    return;
                  }
                  
                  setState(() {
                    _reminderAt = reminderAt;
                  });
                },
              ),
              const SizedBox(height: 8),
              Divider(
                height: 40,
                thickness: 1,
                color: Theme.of(context).colorScheme.outline.withValues(alpha:0.2),
              ),
              Text(
                'Photos (optional)',
                style: Theme.of(context).textTheme.titleMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 12),
              
              // Display selected images
              if (_selectedImages.isNotEmpty)
                SizedBox(
                  height: 120,
                  child: ListView.builder(
                    scrollDirection: Axis.horizontal,
                    itemCount: _selectedImages.length,
                    itemBuilder: (context, index) {
                      return Padding(
                        padding: const EdgeInsets.only(right: 12),
                        child: Stack(
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(12),
                              child: Image.file(
                                _selectedImages[index],
                                width: 120,
                                height: 120,
                                fit: BoxFit.cover,
                              ),
                            ),
                            Positioned(
                              top: 6,
                              right: 6,
                              child: Container(
                                decoration: BoxDecoration(
                                  color: Theme.of(context).colorScheme.error,
                                  shape: BoxShape.circle,
                                ),
                                child: IconButton(
                                  icon: const Icon(Icons.close, size: 18, color: Colors.white),
                                  onPressed: () {
                                    HapticFeedback.lightImpact();
                                    setState(() {
                                      _selectedImages.removeAt(index);
                                    });
                                  },
                                  padding: EdgeInsets.zero,
                                  constraints: const BoxConstraints(
                                    minWidth: 44,
                                    minHeight: 44,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      );
                    },
                  ),
                ),
              
              const SizedBox(height: 12),
              
              // Add photo button
              OutlinedButton.icon(
                onPressed: () {
                  HapticFeedback.lightImpact();
                  _pickImages();
                },
                icon: const Icon(Icons.add_photo_alternate),
                label: const Text('Add Photos'),
                style: OutlinedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 14),
                  minimumSize: const Size(0, 44), // Minimum touch target
                ),
              ),
              const SizedBox(height: 32),
              Row(
                children: [
                  Expanded(
                    child: OutlinedButton(
                      onPressed: _isLoading ? null : () {
                        HapticFeedback.lightImpact();
                        Navigator.pop(context);
                      },
                      style: OutlinedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        minimumSize: const Size(0, 44), // Minimum touch target
                      ),
                      child: const Text('Cancel'),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    flex: 2,
                    child: ElevatedButton(
                      onPressed: _isLoading ? null : _handleSave,
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        minimumSize: const Size(0, 44), // Minimum touch target
                      ),
                      child: _isLoading
                          ? const SizedBox(
                              height: 20,
                              width: 20,
                              child: CircularProgressIndicator(strokeWidth: 2),
                            )
                          : const Text('Save'),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 20),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildDatePickerTile(
    BuildContext context, {
    required String title,
    required String value,
    required IconData icon,
    required VoidCallback onTap,
    bool hasClear = false,
    VoidCallback? onClear,
  }) {
    final isNotSet = value == 'Not set';
    
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(12),
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: Theme.of(context).colorScheme.surfaceContainerHighest.withValues(alpha:0.5),
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: Theme.of(context).colorScheme.outline.withValues(alpha:0.2),
          ),
        ),
        child: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: Theme.of(context).colorScheme.primary.withValues(alpha:0.1),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Icon(
                icon,
                size: 20,
                color: Theme.of(context).colorScheme.primary,
              ),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    title,
                    style: Theme.of(context).textTheme.bodySmall?.copyWith(
                      color: Theme.of(context).colorScheme.onSurface.withValues(alpha:0.6),
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    value,
                    style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                      color: isNotSet 
                          ? Theme.of(context).colorScheme.onSurface.withValues(alpha:0.5)
                          : Theme.of(context).colorScheme.onSurface,
                      fontWeight: isNotSet ? FontWeight.normal : FontWeight.w500,
                    ),
                  ),
                ],
              ),
            ),
            if (hasClear && onClear != null)
              IconButton(
                icon: Icon(
                  Icons.clear,
                  size: 20,
                  color: Theme.of(context).colorScheme.onSurface.withValues(alpha:0.6),
                ),
                onPressed: () {
                  HapticFeedback.lightImpact();
                  onClear();
                },
                padding: EdgeInsets.zero,
                constraints: const BoxConstraints(
                  minWidth: 44,
                  minHeight: 44,
                ),
              ),
            const SizedBox(width: 8),
            Icon(
              Icons.chevron_right,
              color: Theme.of(context).colorScheme.onSurface.withValues(alpha:0.4),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildCategorySelector(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: Theme.of(context).colorScheme.surfaceContainerHighest.withValues(alpha:0.5),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(
          color: Theme.of(context).colorScheme.outline.withValues(alpha:0.2),
        ),
      ),
      child: InkWell(
        onTap: () => _showCategoryPicker(context),
        borderRadius: BorderRadius.circular(12),
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: Theme.of(context).colorScheme.primary.withValues(alpha:0.1),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Icon(
                  Icons.category,
                  size: 20,
                  color: Theme.of(context).colorScheme.primary,
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Category (optional)',
                      style: Theme.of(context).textTheme.bodySmall?.copyWith(
                        color: Theme.of(context).colorScheme.onSurface.withValues(alpha:0.6),
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      _category ?? 'Not set',
                      style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                        color: _category == null
                            ? Theme.of(context).colorScheme.onSurface.withValues(alpha:0.5)
                            : Theme.of(context).colorScheme.onSurface,
                        fontWeight: _category == null ? FontWeight.normal : FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
              if (_category != null)
                IconButton(
                  icon: Icon(
                    Icons.clear,
                    size: 20,
                    color: Theme.of(context).colorScheme.onSurface.withValues(alpha:0.6),
                  ),
                  onPressed: () {
                    HapticFeedback.lightImpact();
                    setState(() {
                      _category = null;
                    });
                  },
                  padding: EdgeInsets.zero,
                  constraints: const BoxConstraints(
                    minWidth: 44,
                    minHeight: 44,
                  ),
                ),
              const SizedBox(width: 8),
              Icon(
                Icons.chevron_right,
                color: Theme.of(context).colorScheme.onSurface.withValues(alpha:0.4),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Future<void> _showCategoryPicker(BuildContext context) async {
    HapticFeedback.lightImpact();
    final TextEditingController customCategoryController = TextEditingController();
    
    final result = await showDialog<String>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Select Category'),
        content: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              // Predefined categories
              ..._predefinedCategories.map((category) => ListTile(
                title: Text(category),
                selected: _category == category,
                selectedTileColor: Theme.of(context).colorScheme.primaryContainer,
                onTap: () {
                  HapticFeedback.mediumImpact();
                  Navigator.pop(context, category);
                },
                trailing: _category == category
                    ? Icon(
                        Icons.check,
                        color: Theme.of(context).colorScheme.primary,
                      )
                    : null,
              )),
              const Divider(),
              // Custom category option
              ListTile(
                leading: const Icon(Icons.add),
                title: const Text('Add Custom Category'),
                onTap: () async {
                  Navigator.pop(context);
                  // Show dialog for custom category
                  await Future.delayed(const Duration(milliseconds: 200));
                  final customCategory = await showDialog<String>(
                    context: context,
                    builder: (context) => AlertDialog(
                      title: const Text('Custom Category'),
                      content: TextField(
                        controller: customCategoryController,
                        autofocus: true,
                        decoration: const InputDecoration(
                          labelText: 'Category Name',
                          hintText: 'Enter category name',
                          border: OutlineInputBorder(),
                        ),
                        textCapitalization: TextCapitalization.words,
                      ),
                      actions: [
                        TextButton(
                          onPressed: () {
                            HapticFeedback.lightImpact();
                            Navigator.pop(context);
                          },
                          style: TextButton.styleFrom(
                            minimumSize: const Size(88, 44),
                          ),
                          child: const Text('Cancel'),
                        ),
                        ElevatedButton(
                          onPressed: () {
                            final category = customCategoryController.text.trim();
                            if (category.isNotEmpty) {
                              HapticFeedback.mediumImpact();
                              Navigator.pop(context, category);
                            } else {
                              HapticFeedback.lightImpact();
                            }
                          },
                          style: ElevatedButton.styleFrom(
                            minimumSize: const Size(88, 44),
                          ),
                          child: const Text('Add'),
                        ),
                      ],
                    ),
                  );
                  if (customCategory != null && mounted) {
                    setState(() {
                      _category = customCategory;
                    });
                  }
                },
              ),
              // Clear category option
              if (_category != null)
                ListTile(
                  leading: Icon(
                    Icons.clear,
                    color: Theme.of(context).colorScheme.error,
                  ),
                  title: Text(
                    'Clear Category',
                    style: TextStyle(
                      color: Theme.of(context).colorScheme.error,
                    ),
                  ),
                  onTap: () {
                    HapticFeedback.lightImpact();
                    Navigator.pop(context, '');
                  },
                ),
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () {
              HapticFeedback.lightImpact();
              Navigator.pop(context);
            },
            style: TextButton.styleFrom(
              minimumSize: const Size(88, 44),
            ),
            child: const Text('Cancel'),
          ),
        ],
      ),
    );

    if (result != null && mounted) {
      setState(() {
        _category = result.isEmpty ? null : result;
      });
    }
  }
}

